name: simpletodo
description: Create ToDo list.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.3 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/login/
    - assets/lang/
  fonts:
    - family: FreestyleScript
      fonts:
        - asset: assets/fonts/FreeScript.ttf
    - family: Exo
      fonts:
        - asset: assets/fonts/Exo_Medium.ttf
          style: normal
        - asset: assets/fonts/Exo_MediumItalic.ttf
          style: italic
