name: simpletodo
description: Create ToDo list.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.3 <3.0.0"

dependencies:
  cloud_firestore: ^4.13.6
  cupertino_icons: ^1.0.2
  email_validator: ^2.1.17
  firebase_auth: ^4.15.3
  firebase_core: ^2.24.2
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_localizations:
    sdk: flutter
  fluttertoast: ^8.2.4

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/app_icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/icons/app_icon.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/icons/app_icon.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/icons/app_icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/login/
    - assets/lang/
    - assets/icons/
  fonts:
    - family: FreestyleScript
      fonts:
        - asset: assets/fonts/FreeScript.ttf
    - family: Exo
      fonts:
        - asset: assets/fonts/Exo_Medium.ttf
          style: normal
        - asset: assets/fonts/Exo_MediumItalic.ttf
          style: italic
